### ISSUE TITLE
I want to provide a korean language strings

### ISSUE THREAD

**Issue by yeonggille** [ClosureTalk/closure-talk#18]
和平与你同在, 先生.
I am a native korean and I know the korean strings for the blue archive, if you okay,
then Could I provide you the korean string and make a korean locale page?
I meant for the blue archive, but if you, 先生 wants, then I also can research for the arknights.
Thank you, have a nice day.

**Comment by logchan** [comment]
Thanks for your interest in helping! I'd love to add Korean, so first I need to make some code changes. Also I should write a document about how to provide translations. So, I'll do these two things first, and get back to you when it's ready to receive new translations.

Hopefully it'll be ready in one or two weeks.

**Comment by yeonggille** [comment]
Thank you for your kindness, I will be wait for it

**Comment by yeonggille** [comment]
Okay, I decided to research korean locale for arknights too after I do the blue archive, for thanks to your kindness. Could you make a way to modify string for arkinghts too? Thank you.

**Comment by yeonggille** [comment]
先生, I found out that korean strings are almost settled. I am really happy for your hard work of cooperation,
But I found a little bugs that School names printed as 學校, Not 학교
And gematria (Including black suit and other members) and Arona is missing, and last, the normal students are printed as a japanese language. If you need a help, then Please don't hesitate to ask me. thank you, have a nice day.

**Comment by logchan** [comment]
Hi, thanks for the patience! I spent some time to organize the code handling character name translations.

I added Korean support to the app, and tried to obtain character names from the official resources when possible (that's why you see some strings there). I don't know Korean actually, so many of them (mostly NPCs) are still missing and falling back to Japanese. So it'd be very helpful if you can look at those.

I put together these documents on how translation works [for the app](https://github.com/ClosureTalk/closure-talk/tree/master/docs/localization) and [for Blue Archive characters](https://github.com/ClosureTalk/closure-talk/tree/master/docs/localization/blue-archive). Let me know if anything is unclear.

For Arknights I think the official data is good enough for released characters. Don't worry about those... Blue Archive is already quite a lot.

**Comment by yeonggille** [comment]
I understand the how the process go. I will check about the mistranslation for gits when I have a time, I appreciate you!

**Comment by AemonJape** [comment]
Due to those documents on how to contribute translation, I have submitted pull requests for blue archive and the Korean UI. 
Now that directions are given, I think we can consider this issue closed.

**Comment by yeonggille** [comment]
Oh, sorry that I left remain opened. I will close this one.
Thanks for the kind reminder!
